networks:
  my-network:
    external: true
    driver: bridge

volumes:
  mysql_data:
  postgres:
  postgres_data:
  mongo_data:
  rabbitmq_data:
  rabbitmq_log:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123_password
      - TZ=America/Sao_Paulo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts-mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s
    networks:
      - my-network

  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=123_password
      - TZ=America/Sao_Paulo
    volumes:
      - postgres:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts-postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - my-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U sonar -d sonar -h localhost",
        ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123_password
      - TZ=America/Sao_Paulo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://root:123_password@localhost:27017/ --quiet
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_PASS=123_password
      - TZ=America/Sao_Paulo
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s
    networks:
      - my-network