global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "mysqld_exporter"
    params:
      auth_module: [client]
    scrape_interval: 25s
    static_configs:
      - targets: ['mysql:3306']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysql_exporter:9104

  - job_name: "postgres_exporter"
    scrape_interval: 25s
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:9188"]

  - job_name: "uptime_kuma"
    scrape_interval: 25s
    scheme: http
    static_configs:
      - targets: ['uptime-kuma:3001']
    basic_auth: 
      password: "uk3_QmghPKmZPq34yL4D07Mn2J8vnoaKxa602R7svlOa"