-- sonar
CREATE DATABASE sonar;
CREATE USER sonar WITH PASSWORD 'sonar';
GRANT ALL PRIVILEGES ON DATABASE sonar TO sonar;
\c sonar
GRANT ALL PRIVILEGES ON SCHEMA public TO sonar;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO sonar;

-- ipool
CREATE DATABASE ipool_db;
CREATE USER ipool_user WITH PASSWORD '123_password';
GRANT ALL PRIVILEGES ON DATABASE ipool_db TO ipool_user;
\c ipool_db
GRANT ALL PRIVILEGES ON SCHEMA public TO ipool_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ipool_user;